### ISSUE TITLE
ontic.nginx | Nginx | RedHat | Install latest Nginx version [Errno 256] No more mirrors to try.

### ISSUE THREAD

**Issue by MikeiLL** [ontic/ansible-role-nginx#1] opened 2015-10-29 03:38 UTC
On AWS EC2 server I'm getting following error:

nginx: [Errno 256] No more mirrors to try.
Could not match packages: failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.

The AWS OS is somewhere between RedHat and CentOS from what I understand.

Any thoughts?

**Comment by adamdyson** [comment] 2015-10-29 07:42
Thanks for reporting this, I'll investigate further once I get home and hopefully provide a fix/solution in a couple of hours.

Cheers,
Adam

**Comment by adamdyson** [comment] 2015-10-29 10:31
Hi @MikeiLL 

I can't replicate this issue myself, can you tell me what version of CentOS you're using? The error you received is likely caused by stale packages and or headers, can you please make sure the `[nginx]` repository is enabled (which is by default) see the [nginx.repo.j2](https://github.com/ontic/ansible-role-nginx/blob/master/templates/nginx.repo.j2) template. By running this command:

```
yum --enablerepo=nginx
```

I'd be interested to see whether running either of these commands fixes your problem. I've written a short description for each.

```
yum clean headers
```

Eliminate all of the files which yum uses to determine the remote availability of packages.

```
yum clean packages
```

Eliminate any cached packages from the system.

```
yum clean all
```

Runs yum clean packages and yum clean headers as above.

The `yum clean all` command will not only remove cached packages, but also any headers. I do it occasionally to totally flush out everything in case there are obsolete headers - which can also take up space, albeit not very much. The reason it takes a little longer next time you run "yum update" is because that cache of headers needs to be replenished.

Let me know if this helps or needs further investigation. Here's an image after I provisioned a CentOS 7 VM just as you described.

![Proof](http://s24.postimg.org/z7txpfeit/vagrant_nginx.jpg)

**Comment by MikeiLL** [comment] 2015-10-29 15:53
Hi @adamdyson and thanks for responding so quickly. It's actually not CentOS, it's Amazon's own version of Linux (similar to CentOS and Red Hat) and I was trying to incorporate this repo into a fairly complicated (by my standards - don't laugh) deployment script https://github.com/MikeiLL/ofn_deployment_ec2 that I have been porting over from an apt-based ubuntu system. But since last night I realized (I've got a lot to learn) that AWS provides ubuntu images and am going that route. 

Is there something (simple) I can do in the AWS Linux server that would be helpful to you? Otherwise I think I'm ready to abandon this approach all together. Not even sure how long I'll stick with EC2, but it's been a good learning tool for sure.

**Comment by adamdyson** [comment] 2015-10-30 08:09
Ok @MikeiLL so none of the commands above helped at all? Before you give up on Amazon Linux, I'd be interested to see whether naming the repository to something other than `[nginx]` would fix the problem? I'm yet to play around with AWS as my day job keeps me pretty busy, but I'm curious as to whether Amazon's custom version of CentOS already includes some extra repositories/packages, in particular one called `[nginx]` and it's conflicting with ours.

A simple way of testing this would be to edit this [line](https://github.com/ontic/ansible-role-nginx/blob/master/tasks/package.yml#L84) and change it to something like `your.nginx.repo`. Then in the template file change this [line](https://github.com/ontic/ansible-role-nginx/blob/master/templates/nginx.repo.j2#L3) to match. Be sure to clean all package cache before running your playbook again.

If you would still like my assistance, providing me the output after running these commands would surely help:

```
yum repolist
```

```
yum info nginx
```

Cheers,
Adam

**Comment by adamdyson** [comment] 2015-11-06 10:55
I'll close this issue for now. I can't be certain there's anything I can/should change with the role, or whether the problem is caused by something out of my control.

**Closed as completed by adamdyson** 2015-11-06 10:55 UTC
